services:
  n8n:
    image: n8nio/n8n:1.39.0
    restart: always
    ports:
      - "5678:5678"

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER={N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD={N8N_BASIC_AUTH_PASSWORD}

      - WEBHOOK_URL=http://localhost:5678/
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false

      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    volumes:
      - ./n8n_data:/home/node/.n8n  # CAMINHO RELATIVO PARA OS DADOS DO N8N
      - ./apache_logs:/apache_logs_host  # monta os logs do Apache no n8n
    networks:
      - n8n_network

  apache-target:
    image: httpd:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./apache_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache_www:/usr/local/apache2/htdocs/ # CAMINHO RELATIVO PARA ARQUIVOS HTML
      - ./apache_logs:/usr/local/apache2/logs/
    networks:
      - n8n_network

  # kali-linux:
  #   build: ./kali_linux
  #   restart: always
  #   # volumes:
  #   networks:
  #     - n8n_network

networks:
  n8n_network:
    driver: bridge